-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgXi8/zOfa3UUlQHVNCcapQxHkpstK+FDrZlSEVKDLC+qgCgYIKoZIzj0DAQehRANCAAR8XbGtzT6B3ffSZy5OQUlIaWON2hBks+oBAcyRJCUHeIgiwYS0DAiI2RveLNd/OXkF3fUEe62h+zU/IBLuWlEd
-----END PRIVATE KEY-----